version: "3.9"

services:

  postgres:
    image: postgres:18
    container_name: ecommerce-postgres
    restart: always

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql

    networks:
      - ecommerce-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper

    ports:
      - "2181:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

    networks:
      - ecommerce-network

  kafka:
      image: confluentinc/cp-kafka:7.5.0
      container_name: kafka

      depends_on:
        - zookeeper

      ports:
        - "9092:9092"

      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      networks:
        - ecommerce-network


  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
    networks:
      - ecommerce-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - kafka
    networks:
      - ecommerce-network

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "8087:8087"
    depends_on:
      - postgres
    networks:
      - ecommerce-network

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8088:8088"
    depends_on:
      - kafka
    networks:
      - ecommerce-network

volumes:
  postgres-data:

networks:
  ecommerce-network: